version: "3"

services:
  app:
    depends_on:
      - db
    # runs on raspberry pi as well
    image: flowolf/webtrees:latest
    ports:
      - 1000:80
    restart: unless-stopped
    volumes:
      - app_data:/var/www/webtrees/data/
      - app_media:/var/www/webtrees/media/

  db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: "webtrees"
      MYSQL_USER: "webtrees"
      MYSQL_ROOT_PASSWORD: "badpassword"
      MYSQL_USER_PASSWORD: "badpassword"
    # runs on raspberry pi as well
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  app_media:
    driver: local